name: Build and Release CercubePlus on new commit

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      cercube_version:
        description: "The version of Cercube"
        default: "5.3.11"
        required: true
        type: string
      decrypted_youtube_url:
        description: "The direct URL to the decrypted YouTube ipa"
        default: "https://und3fy-my.sharepoint.com/personal/1decrypt_und3fy_onmicrosoft_com/_layouts/15/download.aspx?SourceUrl=%2Fpersonal%2F1decrypt%5Fund3fy%5Fonmicrosoft%5Fcom%2FDocuments%2FPublic%2FIPAs%2Fid544007664%2Fcom%2Egoogle%2Eios%2Eyoutube%5F18%2E22%2E9%5Fund3fined%2Eipa"
        required: true
        type: string
      youtube_version:
        description: "The version of YouTube"
        default: "18.22.9"
        required: true
        type: string
      bundle_id:
        description: "Modify the bundle ID. Not recommended"
        default: "com.google.ios.youtube"
        required: true
        type: string
      app_name:
        description: "Modify the name of the app on the Home Screen. Not recommended"
        default: "YouTube"
        required: true
        type: string
      create_release:
        description: "Create a draft release"
        default: true
        required: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build CercubePlus
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v3.5.2
        with:
          path: main
          submodules: recursive

      - name: Install Dependencies
        run: brew install ldid dpkg make

      - name: Setup Theos
        uses: actions/checkout@v3.5.2
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive

      - name: Caching
        id: SDK
        uses: actions/cache@v3.3.1
        env:
          cache-name: iOS-15.5-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}

      - name: Download iOS 15.5 SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          svn checkout -q https://github.com/chrisharper22/sdks/trunk/iPhoneOS15.5.sdk
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Setup Theos Jailed
        uses: actions/checkout@v3.5.2
        with:
          repository: qnblackcat/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        run: |
          ./theos-jailed/install
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Download Cercube & Prepare YouTube iPA
        run: |
          curl "https://raw.githubusercontent.com/Muirey03/RemoteLog/master/RemoteLog.h" --output "$THEOS/include/RemoteLog.h"
          curl "https://dl.dropboxusercontent.com/s/b01erqbp3ajc5e2/me.alfhaily.cercube_${{ env.CERCUBE_VERSION }}_iphoneos-arm.deb" --output "main/Tweaks/Cercube/me.alfhaily.cercube_${{ env.CERCUBE_VERSION }}_iphoneos-arm.deb"
          echo -e "==> \033[1mCercube v${{ inputs.cercube_version }} downloaded! \033[0m"
          wget "$YOUTUBE_URL" --no-verbose -O main/YouTube.ipa
          echo -e "==> \033[1mYouTube v${{ inputs.youtube_version }} downloaded! \033[0m"
          cd main/Tweaks/Cercube && tar -xf "me.alfhaily.cercube_5.3.11_iphoneos-arm.deb" && tar -xf data.tar.* && cd ../../..
          echo -e "==> \033[1mCercube v${{ inputs.cercube_version }} unpacked! \033[0m"
          unzip -q main/YouTube.ipa -d main/tmp
          rm -rf main/tmp/Payload/YouTube.app/_CodeSignature/CodeResources
          rm -rf main/tmp/Payload/YouTube.app/PlugIns/*
          cp -R main/Extensions/*.appex main/tmp/PTo add a README file to your GitHub repository, you can follow these steps:

1. Navigate to your repository on GitHub and click on the "Add file" button.
2. Select "Create new file" from the dropdown menu.
3. In the "Name your file..." field, type "README.md".
4. Add content to your README file using Markdown syntax. You can include a project description, setup instructions, usage examples, and any other information you want to share with users.
5. Preview your README file by clicking on the "Preview" tab.
6. When you're satisfied with your README file, click on the "Commit new file" button at the bottom of the page.

Your README file will now be visible on your repository's main page. It will also be displayed on the GitHub repository landing page if you decide to make your repository public. A good README file can help users understand what your project is about, how to use it, and how to contribute to it.
